name = "rsslookup"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "worker/index.ts"

routes = [
  { pattern = "www.rsslookup.com", custom_domain = true }
]

[assets]
directory = "dist/client"
binding = "ASSETS"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "rsslookup_analytics"
